### ISSUE TITLE
Chessborad size issue on A0 paper

### ISSUE THREAD

**Issue by quhezheng** [mfxox/ILCC#1]
"These data are acquired with the chessboard file which contains 6*8 patterns and the length of one grid is 7.5cm if it is printed by A0 size."
    I'm very confused by the statement. The number here doesn't add up. A0 size is 841mm x 1189mm, why the 6*8 patterns with grid 7.5cm could cover A0 size paper? I think the grids pattern is 400mm X 600mm, which can be covered by A1 size paper. Am I right?

**Comment by mfxox** [comment]
The  6*8 patterns  will not just fit the whole A0 size paper, and you need to cut the needless part of the paper. It can be seen that the chessboard is in the left upper part and there is much white space in the downloaded chessboard pdf file. If you print the this pdf in A0 size, the grid will be 7.5cm. But you need to cut the white space.
