### ISSUE TITLE
Corners detection from Point Cloud is wrong.

### ISSUE THREAD

**Issue by DinoBN** [mfxox/ILCC#10]
**<< Description >>**
after run the code of "6.Non-linear optimization for final extrinsic parameters."
output data 0001_cal_backproj.png 〜 0004_cal_backproj.png is obviously wrong.

"img_corners_est" is successfully corners detected.
but, the corners from point cloud data doesn't match the corners from img data.

Do I need to change config.yaml from the default value to work with the data "ILCC_sample_perspective_data"?

If so, please let me know the setting value.

**<< Details >>**
I installed　the most recent version ILCC 
and run with the sample data "ILCC_sample_perspective_data".

about config.yaml
I changed the below parameters. 
 'base_dir' : the data directory
 'poses_num' : 20 → 4 (there are only 4 data at the sample data)

After the command "LM_opt.cal_ext_paras()".
the contents of "YYYYMMDD_HHMMSS_calir_result.txt" is below.

4.715408122537658286e+00
2.337674434525445211e+00
1.106741906490246730e-01
9.065658045971332069e-01
2.508680940249127245e-01
-2.121439663123081965e-01

**<< Verification >>**

I tried only the code "After the aforementioned process, utility module can be imported for visualizing various of results. "
with "ILCC_sample_perspective_data"

and the output data 0001_cal_backproj.png 〜 0004_cal_backproj.png is well.
After the command "LM_opt.cal_ext_paras()".
the contents of "YYYYMMDD_HHMMSS_calir_result.txt" is below.

1.338479622733038943e-01
-1.524339677023719419e+00
1.441150134721521425e+00
-6.890869881762318530e-03
-1.935656845054284925e-01
-3.367990535562562227e-01

**<< My Environment >>**
OS : Ubuntu16.04 64bit
ILCC          : most recent version ILCC (now 2019/1/10)
OpenCV        : 3.3.1-dev
MATLAB        : 9.5.0.944444(R2018b)
PCL           : 1.7
VTK           : 8.1.1
python        : 2.7.15

![0001_cal_backproj](https://user-images.githubusercontent.com/46744050/51239952-0a5f2900-19be-11e9-8403-df2384fa813c.png)
![0001_orig_dis_hide_occlusion](https://user-images.githubusercontent.com/46744050/51239954-0af7bf80-19be-11e9-9b7b-4726dbb08be8.png)
![alldetectedchessboard](https://user-images.githubusercontent.com/46744050/51239955-0af7bf80-19be-11e9-951b-89f4dccea35b.png)
![detectedpointclouchessboard](https://user-images.githubusercontent.com/46744050/51239956-0af7bf80-19be-11e9-9452-5118a5aa7155.png)

**Comment by mfxox** [comment]
@DinoBN Thank you for your detailed report.
As you mentioned in the estimated pcd corner figure with the ***utility.vis_ested_pcd_corners()*** command, the corner seems not correctly estimated.

 A well estimated corner result should be visualized like the following, blue and red points are arranged like chess pattern.  And there is no chess-pattern like in your result. ![here](https://github.com/mfxox/ILCC/raw/master/readme_files/vis_est_marker.png)

From this point, we can assume that the column of the intensity is not set correctly. 
In the sample data, the intensity column  of the point cloud csv file is 3 (counting starts from 0), so you need to change *intensity_col_in* to 3 in ```config.yaml``` .
