### ISSUE TITLE
when VLP-16 pack will add into current repository

### ISSUE THREAD

**Issue by LittleByLittle2** [mfxox/ILCC#12]
Hi, I found the current method is only supported VLP-32, but VLP-16 is not supported, I am wondering when the VLP-16 will be supported?

**Comment by mfxox** [comment]
@LittleByLittle2 VLP-16 is already supported, you can just set 'LiDAR_type' to "vlp16_puck" in the config.yaml file.

**Comment by LittleByLittle2** [comment]
> @LittleByLittle2 VLP-16 is already supported, you can just set 'LiDAR_type' to "vlp16_puck" in the config.yaml file.

Thanks.
