### ISSUE TITLE
IndexError: too many indices for array in PCD corner detection 

### ISSUE THREAD

**Issue by bsridatta** [mfxox/ILCC#15]
Give index error when passing CSV file for corner detection. CSV has 5000+ rows of VLP-16 lidar.

Is there any easy way to convert bag to csv or pcd to csv of the format suggested?
The normal Velodyne_points topic to csv does not have columns like : laser_id | azimuth | distance | timestamp
it has only x,y,z, intensity and ring

**Comment by mfxox** [comment]
You can try this pcd2ILCCcsv [script](https://github.com/mfxox/ILCC/tree/master/scripts
) contributed by @jacoblambert.

**Comment by bsridatta** [comment]
Thanks I missed it somehow
