### ISSUE TITLE
Would the code work with monocular camera?

### ISSUE THREAD

**Issue by quhezheng** [mfxox/ILCC#2]
I'm using the code to calibration the extrinsic parameter of  velodyne 64S3 and monocular camera. But the samples are working with panoramic camera, would it work well with monocular camera?

**Comment by mfxox** [comment]
The proposed intensity-based method is also able to work with perspective camera or other 3D sensors. However, the implementation for perspective cameras is still under development.

**Comment by mfxox** [comment]
Implemented
