### ISSUE TITLE
Question on Camera and LiDAR Type

### ISSUE THREAD

**Issue by dejongyeong** [mfxox/ILCC#23]
Hi, Thanks for providing a tool for camera-lidar sensor calibration.

I would like to ask is this camera-lidar calibration tool applicable for a monocular camera and a VLP-32C Velodyne 3D LiDAR?

Thanks.

**Comment by poornimajd** [comment]
@dejongyeong were you able to get it working for lidar VLP-32C?
Thanks.

**Comment by dejongyeong** [comment]
@poornimajd unfortunately I did not got a chance to use this package for calibrations - not using MATLAB
