### ISSUE TITLE
Problem in test VLP32c

### ISSUE THREAD

**Issue by Rockyzyk** [mfxox/ILCC#4]
@mfxox 
Hi, mfxox

I have the other problem in using VLP32c,
the Vertical Angular Resolution of this sensor is non-linear distribution. 
So we can not use the same vertical angular resolution to verify the segment.

Would you please tell me, is it any solution to solve this problem?
And how can I modify the code?

Thanks, again!

**Comment by mfxox** [comment]
Hi, Rockyzyk 

I checked  vertical angular resolution of VLP32c and found that although the angular intervals between laser beams are not linear, most intervals are  0.333 deg or 0.667 deg.

I think we can set  vertical angular resolution as 0.333 deg  approximately. (Then, try to adjust "agglomerative_cluster_th_ratio" in config.yaml for the best result.)
I don't have VLP32c now, so can't test it yet.
You can have a try with the master version, in which "vlp32c"  can be set as a valid "LiDAR_type"  in config.yaml.
Of course, it is appreciated if you can share your test data with VLP32c.

**Comment by Rockyzyk** [comment]
THANKS, we test it as you advice and succeed.

**Comment by poornimajd** [comment]
> THANKS, we test it as you advice and succeed.

@Rockyzyk can you please let me know what was the size of your checkerboard grid? I am trying to use vlp-32c,but it always shows marker not found in the point cloud.I have a A1 size paper with 7cm as the grid size.Was there any other change you had to make for the code to make it work for vlp 32c? Any suggestion is appreciated.
Thanks
